### ISSUE TITLE
indicator isn't visible after called first time

### ISSUE THREAD

**Issue by Galleria** [jinhduong/ng2-loading-indicator#1]
Hi,
when I called this indicator it worked fine when called first time but when call next time the indicator isn't show correctly.

-> call() [first time] [work!!]
-> call() [next time] [indicator not working]

Thanks,

```javascript
@LoadingIndicator()
    search(){
        return
            this.service.searchUserByKeyword(this.searchTxt).map(
                (res)=>{
                    this.resultlist =  res[1].data.test
                    console.log( 'finish' )
                }
            )
            .subscribe( ()=> { console.log( 'finished' ) })
    }

**Comment by jinhduong** [comment]
- As for the above example, I think it'll work anytime. So you can debug in this line in your `web developer` to handle what was happen?https://github.com/jinhduong/ng2-loading-indicator/blob/cb817112e62e858042b08a2f8b5956c12887ba05/ng2-simple-loading.decorator.ts#L26-L33


- Better if you change `.map` function to `.do` function. Because `.map` need to return an object, but `.do` will stop the stream and execute the function.

- Btw, you can try the below
``` js
@LoadingIndicator()
async search(){
   const  result = await this.service.searchUserByKeyword.map(res=>...).toPromise();
   // work with result
}
```

**Comment by Galleria** [comment]
Thanks for your suggestion,
After I changed subscribe() to do() and then it works fine.

```javaScript
@LoadingIndicator()
search(){
        return
            this.service.searchUserByKeyword(this.searchTxt).map(
                (res)=>{
                    this.resultlist =  res[1].data.test
                    console.log( 'finish' )
                }
            )
            .do( ()=> { console.log( 'finished' ) })
    }
